"""mimetype

Revision ID: fbb90f77d108
Revises: 36f7971f71a1
Create Date: 2017-12-08 00:22:17.380071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb90f77d108'
down_revision = '36f7971f71a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drop', 'mimetype')
    op.add_column('drop_file', sa.Column('mimetype', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drop_file', 'mimetype')
    op.add_column('drop', sa.Column('mimetype', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
