version: '3'
services:
  backend:
    build: backend
    image: nuqlya/vobla-api:latest
    ports:
      - '${VOBLA_API_PORT}:5000'
    depends_on:
      - postgres
      - redis
    environment:
      - TORNADO_SECRET_KEY=${TORNADO_SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
  postgres:
    image: postgres:9.3
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  redis:
    image: redis:alpine
    command: redis-server --logfile /dev/null
