version: '3'
services:
  vobla-api-service:
    command: ["bash", "./wait-for-postgres.sh", "python manage.py --migrate runserver"]
    volumes:
      - ./wait-for-postgres.sh:/wait-for-postgres.sh
      - ./volumes/vobla:/var/vobla
    depends_on:
      - mongo-service
      - redis-service
      - postgres-service
    environment:
      - 'ENV=prod'
  mongo-service:
    volumes:
      - ./volumes/mongodb/data/db:/data/db
  postgres-service:
    volumes:
      - ./volumes/postgres/var/lib/postgresql/data:/var/lib/postgresql/data
  vobla-frontend-service:
    build: frontend
    image: nuqlya/vobla-frontend:latest
    command: npm run build
    depends_on:
      - vobla-api-service
    volumes:
      - ./frontend/build:/build
  swagger-ui-service:
    image: swaggerapi/swagger-ui
    depends_on:
      - vobla-api-service
    environment:
      - 'API_URL=https://vobla.olegshigor.in/api/open_api2.json'
    ports:
      - '${VOBLA_SWAGGER_PORT}:8080'
