version: '3.5'
services:
  backend:
    command: ["bash", "./wait-for-postgres.sh", "python manage.py runtests"]
    volumes:
      - ./backend/vobla:/vobla
      - ./backend/manage.py:/manage.py
      - ./backend/tests:/tests
      - ./backend/alembic:/alembic
      - ./wait-for-postgres.sh:/wait-for-postgres.sh
    environment:
      - ENV=tests
      - POSTGRES_DB=test_db
  postgres:
    image: postgres:9.3
    environment:
      - POSTGRES_DB=test_db
    volumes:
      - db-test-data:/var/lib/postgresql/data

volumes:
  db-test-data:
