version: '3.5'
services:
  backend:
    image: nuqlya/vobla-api:latest
    ports:
      - '${VOBLA_API_PORT}:5000'
    depends_on:
      - postgres
      - redis
      - ssdb
      - minio
    environment:
      - TORNADO_SECRET_KEY=${TORNADO_SECRET_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_HOST=minio
      - MINIO_PORT=${MINIO_PORT}
  postgres:
    image: postgres:9.3
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  redis:
    image: redis:alpine
    command: redis-server --logfile /dev/null
  ssdb:
    image: leobuskin/ssdb-docker
  minio:
    image: minio/minio
    command:
      server --address :${MINIO_PORT} /data
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}


volumes:
  db-data:
  minio-data:
