version: '3'
services:
  vobla-api-service:
    build: api
    image: nuqlya/vobla-api:latest
    ports:
      - '${VOBLA_API_PORT}:5000'
    depends_on:
      - mongo-service
      - redis-service
      - postgres-service
    env_file: '.env'
  mongo-service:
    image: mongo:3.4.0
    command: mongod --smallfiles --logpath=/dev/null
  redis-service:
    image: redis:alpine
    command: redis-server --logfile /dev/null
  postgres-service:
    image: postgres:9.3
    environment:
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
