version: '3.5'
services:
  backend:
    image: nuqlya/vobla-api:latest
    ports:
      - '${VOBLA_API_PORT}:5000'
    depends_on:
      - postgres
      - redis
      - ssdb
    environment:
      - TORNADO_SECRET_KEY=${TORNADO_SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
  postgres:
    image: postgres:9.3
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  redis:
    image: redis:alpine
    command: redis-server --logfile /dev/null
  ssdb:
    image: leobuskin/ssdb-docker

volumes:
  db-data:
